import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'  show defaultTargetPlatform, kIsWeb, TargetPlatform;

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
   
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyKETO0gkO2jvs9_gnkxJAN5LMJT_APGg',
    appId: '1:1090778445226:web:ec3df7d482b916eb34e7d3',
    messagingSenderId: '1090778445226',
    projectId: 'ist-blood-donors-2025',
    authDomain: 'ist-blood-donors-2025.firebaseapp.com',
    storageBucket: 'ist-blood-donors-2025.firebasestorage.app',
    measurementId: 'G-DRMK5X5B1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlJ2xa6ThzZHIE9a2xCszJnwzShQ4hibY',
    appId: '1:1090778445226:android:f4bc205b83b0ade834e7d3',
    messagingSenderId: '1090778445226',
    projectId: 'ist-blood-donors-2025',
    storageBucket: 'ist-blood-donors-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWi5ZEexqIU5MH8uln7OlUHWqGXfCyB6s',
    appId: '1:1090778445226:ios:71ad9009ee46cf5534e7d3',
    messagingSenderId: '1090778445226',
    projectId: 'ist-blood-donors-2025',
    storageBucket: 'ist-blood-donors-2025.firebasestorage.app',
    iosBundleId: 'com.example.istBloodDonors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWi5ZEexqIU5MH8uln7OlUHWqGXfCyB6s',
    appId: '1:1090778445226:ios:71ad9009ee46cf5534e7d3',
    messagingSenderId: '1090778445226',
    projectId: 'ist-blood-donors-2025',
    storageBucket: 'ist-blood-donors-2025.firebasestorage.app',
    iosBundleId: 'com.example.istBloodDonors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyKETO0gkO2jvs9_gnkxJAN5LMJT_APGg',
    appId: '1:1090778445226:web:9c28cee43d480bdc34e7d3',
    messagingSenderId: '1090778445226',
    projectId: 'ist-blood-donors-2025',
    authDomain: 'ist-blood-donors-2025.firebaseapp.com',
    storageBucket: 'ist-blood-donors-2025.firebasestorage.app',
    measurementId: 'G-Z82LJJ6X9D',
  );
}
